name: Build EXE for Windows with assets and icon

on:
  push:
    branches:
      - main  # 替換成你使用的分支

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with assets and icon
      run: |
        pyinstaller main.py --onefile --windowed --icon=icon.ico --add-data "assets;assets"

    - name: Upload EXE file
      uses: actions/upload-artifact@v4
      with:
        name: my-program
        path: dist/main.exe
